import SobreMiNav from "../../../components/SobreMiNav/SobreMiNav";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   

        <div>
            <SobreMiNav/>
            {children}
        </div>

  );
}
