import SobreMiNav from "../../../components/SobreMiNav/SobreMiNav";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <div className="bg-gradient-to-b from-[#252424] via-[#0A2003] to-[#0B6329] h-full ">
            <SobreMiNav/>
            {children}
        </div>
      </body>
    </html>
  );
}
