import "./globals.css";
import NavBar from "../../components/NavBar/NavBar";
import Footer from "../../components/Footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body cz-shortcut-listen="true">
        <div className="bg-gradient-to-b from-[#252424] via-[#0A2003] to-[#0B6329] h-full  text-white">
          <NavBar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
