import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../../components/NavBar/NavBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gradient-to-b from-[#252424] via-[#0A2003] to-[#0B6329] h-full ">
          <NavBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
